#!/bin/bash
#PBS -l select=4
#PBS -l place=scatter
#PBS -l filesystems=home:flare
#PBS -l walltime=0:15:00
#PBS -A ATPESC2025
#PBS -q ATPESC

cd ${PBS_O_WORKDIR}

# make sure scratch dir exists
SCRATCHDIR=/flare/ATPESC2025/usr/$USER
mkdir -p $SCRATCHDIR

# delete old file if present
rm -rf $SCRATCHDIR/fidgetspinnerA*

# submit job
mpiexec -n 408 --ppn 102 --cpu-bind core ./fidgetspinnerA $SCRATCHDIR
