#!/bin/bash
#COBALT -n 4
#COBALT -t 20
#COBALT --mode script
#COBALT -A ATPESC2019
#COBALT -q R.ATPESC2019

# make sure scratch dir exists
for i in `seq 1 5`; do
    mkdir -p /projects/ATPESC2019/$USER/$i
done

# delete old file if present
for i in `seq 1 5`; do
    rm -rf /projects/ATPESC2019/$USER/$i/variance*
done

# submit job
for i in `seq 1 5`; do
    aprun -n 256 -N 64 ./variance /projects/ATPESC2019/$USER/$i
done
