#!/bin/bash
#COBALT -n 4
#COBALT -t 15
#COBALT --mode script
#COBALT -A ATPESC2021
#COBALT -q ATPESC2021

# make sure scratch dir exists
mkdir -p /projects/ATPESC2021/$USER
# set striping parameters to use all servers
lfs setstripe -c -1 /projects/ATPESC2021/$USER

# delete old file if present
rm -rf /projects/ATPESC2021/$USER/helloworld

# submit job
aprun -n 256 -N 64 ./helloworld /projects/ATPESC2021/$USER/
