#!/bin/bash
#COBALT -n 4
#COBALT -t 15
#COBALT --mode script
#COBALT -A ATPESC2020
#COBALT -q ATPESC2020

# make sure scratch dir exists
mkdir -p /projects/ATPESC2020/$USER
# set striping parameters to use all servers
lfs setstripe -c -1 /projects/ATPESC2020/$USER

# delete old file if present
rm -rf /projects/ATPESC2020/$USER/helloworld

# submit job
aprun -n 256 -N 64 ./helloworld /projects/ATPESC2020/$USER/
