#!/bin/bash
#COBALT -n 4
#COBALT -t 15
#COBALT --mode script
#COBALT -A ATPESC2018
#COBALT -q atpesc_morning

# make sure scratch dir exists
mkdir -p /projects/ATPESC2018/$USER
# set striping parameters to use all servers
lfs setstripe -c -1 /projects/ATPESC2018/$USER

# delete old file if present
rm -rf /projects/ATPESC2018/$USER/warpdriveA

# submit job
aprun -n 256 -N 64 ./warpdriveA /projects/ATPESC2018/$USER/
