#!/bin/bash
#COBALT -n 4
#COBALT -t 15
#COBALT --mode script
#COBALT -A ATPESC2019
#COBALT -q R.ATPESC2019

# make sure scratch dir exists
mkdir -p /projects/ATPESC2019/$USER
# set striping parameters to use all servers
lfs setstripe -c -1 /projects/ATPESC2019/$USER

# delete old file if present
rm -rf /projects/ATPESC2019/$USER/warpdriveB

# submit job
aprun -n 256 -N 64 ./warpdriveB /projects/ATPESC2019/$USER/
