#!/bin/sh
# Some versions of enscript also support
# --style emacs 
enscript -1rC -E --color -f "CourierBold16" \
	--line-numbers \
  -F "CourierBold16" --header='File: $n||Page $% of $=' -w rtf $1 -o $2
